/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuestbookRouteImport } from './routes/guestbook'
import { Route as PetCornerRouteImport } from './routes/pet-corner'
import { Route as RecipeNookRouteImport } from './routes/recipe-nook'
import { Route as ScrapbookRouteImport } from './routes/scrapbook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestbookRoute = GuestbookRouteImport.update({
  id: '/guestbook',
  path: '/guestbook',
  getParentRoute: () => rootRouteImport,
} as any)
const PetCornerRoute = PetCornerRouteImport.update({
  id: '/pet-corner',
  path: '/pet-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipeNookRoute = RecipeNookRouteImport.update({
  id: '/recipe-nook',
  path: '/recipe-nook',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrapbookRoute = ScrapbookRouteImport.update({
  id: '/scrapbook',
  path: '/scrapbook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guestbook': typeof GuestbookRoute
  '/pet-corner': typeof PetCornerRoute
  '/recipe-nook': typeof RecipeNookRoute
  '/scrapbook': typeof ScrapbookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guestbook': typeof GuestbookRoute
  '/pet-corner': typeof PetCornerRoute
  '/recipe-nook': typeof RecipeNookRoute
  '/scrapbook': typeof ScrapbookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guestbook': typeof GuestbookRoute
  '/pet-corner': typeof PetCornerRoute
  '/recipe-nook': typeof RecipeNookRoute
  '/scrapbook': typeof ScrapbookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/guestbook' | '/pet-corner' | '/recipe-nook' | '/scrapbook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/guestbook' | '/pet-corner' | '/recipe-nook' | '/scrapbook'
  id:
    | '__root__'
    | '/'
    | '/guestbook'
    | '/pet-corner'
    | '/recipe-nook'
    | '/scrapbook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuestbookRoute: typeof GuestbookRoute
  PetCornerRoute: typeof PetCornerRoute
  RecipeNookRoute: typeof RecipeNookRoute
  ScrapbookRoute: typeof ScrapbookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guestbook': {
      id: '/guestbook'
      path: '/guestbook'
      fullPath: '/guestbook'
      preLoaderRoute: typeof GuestbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet-corner': {
      id: '/pet-corner'
      path: '/pet-corner'
      fullPath: '/pet-corner'
      preLoaderRoute: typeof PetCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipe-nook': {
      id: '/recipe-nook'
      path: '/recipe-nook'
      fullPath: '/recipe-nook'
      preLoaderRoute: typeof RecipeNookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scrapbook': {
      id: '/scrapbook'
      path: '/scrapbook'
      fullPath: '/scrapbook'
      preLoaderRoute: typeof ScrapbookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuestbookRoute: GuestbookRoute,
  PetCornerRoute: PetCornerRoute,
  RecipeNookRoute: RecipeNookRoute,
  ScrapbookRoute: ScrapbookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
